### ISSUE TITLE
automount on system reboot

### ISSUE THREAD

**Issue by akhiljalagam** [bastiaanvanassche/ansible-role-s3fs-fuse#2]
adding fstab helps solve this issue

**Comment by huntertj** [comment]
akhilin can you provide a sample fstab entry? I'd like to solve this as well

**Comment by akhiljalagam** [comment]
add this line to /etc/fstab file to automount at boot:
mybucket /path/to/mountpoint fuse.s3fs _netdev,allow_other 0 0

reference:
https://github.com/s3fs-fuse/s3fs-fuse

**Comment by akhiljalagam** [comment]
To automate fstab with ansible. check this
https://github.com/4khi1/ansible-role-s3fs/blob/f7a92326a988e45ebdfe6865f2e94f8bd75704c3/tasks/mount.yml#L35
